# keep sorted order
# -- ArgoCD Deployment
argo-cd:
  # -- whether to create the namespace or not
  createNamespace: false
  enable: false

# we install it in kube-system namespace so we don't need to create it
# -- AWS EFS CSI Driver
aws-efs-csi-driver:
  enable: true

# -- Cert Manager
certmanager:
  # -- whether to create the namespace or not
  createNamespace: true
  enable: true

# -- DefectDojo
defectdojo:
  # -- whether to create the namespace or not
  createNamespace: true
  enable: true

dependency-track:
  createNamespace: true
  enable: true

edp:
  createNamespace: true
  enable: true

extensions-oidc:
  createNamespace: true
  enable: true

external-secrets:
  createNamespace: true
  enable: true

# fluent-bit can be installed as a single component
fluent-bit:
  createNamespace: false
  enable: false

harbor:
  createNamespace: true
  enable: true

# Harbor with High Availability
harbor-ha:
  createNamespace: true
  enable: true

# Harbor with HA, OKD Cluster
harbor-ha-okd:
  createNamespace: true
  enable: false

ingress-nginx:
  createNamespace: true
  enable: true

jaeger-operator:
  enable: true
  createNamespace: true

keycloak:
  createNamespace: true
  enable: true

keycloak-postgresql:
  createNamespace: false
  enable: false

minio-operator:
  createNamespace: true
  enable: true

nexus:
  createNamespace: true
  enable: true

# opensearch includes opensearch, opensearch-dashboards, fluent-bit
opensearch:
  createNamespace: true
  enable: true

opentelemetry-operator:
  enable: true
  createNamespace: true

# Postgres Operator
postgres-operator:
  createNamespace: true
  enable: true

prometheus-operator:
  createNamespace: true
  enable: true

redis-operator:
  createNamespace: true
  enable: true

sonar:
  createNamespace: true
  enable: true

sonar-operator:
  createNamespace: true
  enable: true

storage-class:
  enable: true

tekton:
  createNamespace: true
  enable: true

vault:
  createNamespace: true
  enable: true

vault-kms:
  createNamespace: true
  enable: false

vault-okd:
  createNamespace: true
  enable: true
