apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: {{ .Values.extensionsOIDC.sharedService }}-{{ include "broker.name" . }}
spec:
  attributes:
    post.logout.redirect.uris: +
  clientId: {{ .Values.extensionsOIDC.sharedService }}
  clientRoles:
    - administrator
    - developer
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  secret: keycloak-client-shared-secret
