nexus-repository-manager:
  image:
    tag: 3.58.1
  nameOverride: "nexus"
  fullnameOverride: "nexus"

  serviceAccount:
    name: nexus-repo

  ingress:
    enabled: false
    hostRepo: nexus.example.com

  deployment:
    initContainers:
    - name: fmp-volume-permission
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['mkdir','-p', '/nexus-data/etc']
      volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data

  nexus:
    env:
      - name: NEXUS_SECURITY_RANDOMPASSWORD
        value: "false"
    resources:
      limits:
        memory: 6Gi
      requests:
        cpu: 100m
        memory: 2Gi

    properties:
      override: true
      data:
        nexus.scripts.allowCreation: true
        jetty.request.header.size: 100000

  persistence:
    enabled: true
    storageSize: 30Gi

oauth2-proxy:
  config:
    configFile: |-
      allowed_roles = ["administrator", "developer"]
      client_id = "nexus"
      code_challenge_method="S256"
      cookie_csrf_expire="5m"
      cookie_csrf_per_request="true"
      cookie_secure = "false"
      email_domains = [ "*" ]
      insecure_oidc_allow_unverified_email = "true"
      oidc_issuer_url = "https://keycloak.example.com/auth/realms/<cluster_name>"
      pass_access_token = "true"
      pass_authorization_header = "true"
      pass_basic_auth = "false"
      provider = "keycloak-oidc"
      redirect_url = "https://nexus.example.com/oauth2/callback"
      skip_jwt_bearer_tokens = "true"
      upstreams = [ "http://nexus:8081" ]
      whitelist_domains = ["*"]

    existingSecret: oauth2-proxy

  ingress:
    enabled: true
    hosts:
      - nexus.example.com