edp-install:
  global:
    dnsWildCard: example.com
    platform: kubernetes
    gitProvider: github
    dockerRegistry:
      url: "registry.example.com"
      type: "harbor"
      space: "edp"

  sso:
    enabled: true
    keycloakUrl: https://keycloak.example.com
    admins:
      - john@example.com
      - mike@example.com
    developers:
      - john@example.com
      - mike@example.com

  externalSecrets:
    enabled: true
    secretProvider:
      aws:
        role: arn:aws:iam::012345678910:role/AWSIRSA_Shared_ExternalSecretOperatorAccess
    manageEDPInstallSecrets: true
    manageEDPInstallSecretsName: /edp/deploy-secrets

  edp-headlamp:
    config:
      oidc:
        enabled: true
        keycloakUrl: "https://keycloak.example.com"
        clientID: "shared"

  edp-tekton:
    github:
      host: github.com
