{{ if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: eks
spec:
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  secret: keycloak-client-eks-secret
  advancedProtocolMappers: true
  clientId: eks
  directAccess: true
  defaultClientScopes:
    - groups
  targetRealm: eks
  webUrl: "*"
{{ end }}
