{{ if .Values.oidc.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-eks-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: clientSecret
    remoteRef:
      key: /edp/system
      property: keycloak-client-eks-secret.clientSecret
{{ end }}
