apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: defectdojo-extrasecrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
    - secretKey: DD_SOCIAL_AUTH_KEYCLOAK_SECRET
      remoteRef:
        key: /edp/system
        property: defectdojo.oidcClientSecret
