apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: defectdojo-rabbitmq-specific
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: /edp/system
        property: defectdojo.rabbitmq-password
    - secretKey: rabbitmq-erlang-cookie
      remoteRef:
        key: /edp/system
        property: defectdojo.rabbitmq-erlang-cookie
