{{- if .Values.extensionsOIDC.broker.create -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: {{ .Values.extensionsOIDC.broker.name }}
spec:
  keycloakRef:
    kind: ClusterKeycloak
    name: keycloak
  realmName: {{ .Values.extensionsOIDC.broker.name }}
{{- end -}}
