# -- component name
name: sonar-operator
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
image:
  # -- EDP sonar-operator Docker image name. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/sonar-operator)
  repository: epamedp/sonar-operator
  # if not defined then .Chart.AppVersion is used
  # -- EDP sonar-operator Docker image tag. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/sonar-operator/tags)
  tag: 3.1.0
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

# -- Additional volumes to be added to the pod
extraVolumes: []
#  - name: custom-ca
#    secret:
#      defaultMode: 420
#      secretName: custom-ca

# -- Additional volumeMounts to be added to the container
extraVolumeMounts: []
#  - name: custom-ca
#    mountPath: /etc/ssl/certs/CA.crt
#    readOnly: true
#    subPath: CA.crt

# -- URL and secret name which use sonar operator for configuring sonar
sonarUrl: "https://sonar.example.com"
sonarSecret: "sonar-admin"

# -- Integration with keycloak
keycloak:
  enable: true
  keycloakUrl: "https://keycloak.example.com"
  keycloakRealm: "example"