apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore-keycloak
  data:
  - secretKey: username
    remoteRef:
      key: /edp/system2
      property: keycloak-admin-creds.username
  - secretKey: password
    remoteRef:
      key: /edp/system2
      property: keycloak-admin-creds.password
