apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore-kk-postgress
  data:
  - secretKey: password
    remoteRef:
      key: /edp/system2
      property: keycloak-postgresql.password
  - secretKey: postgres-password
    remoteRef:
      key: /edp/system2
      property: keycloak-postgresql.password
