apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: nexus
spec:
  advancedProtocolMappers: true
  clientId: nexus
  defaultClientScopes:
    - groups
    - edp
  secret: keycloak-client-nexus-secret
  targetRealm: sandbox
  webUrl: https://nexus.example.com
