apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fluentbit-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      metadataPolicy: None
      property: fluentbit.username
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /edp/system
      metadataPolicy: None
      property: fluentbit.password
