sonarqube:
  ingress:
    enabled: true
    hosts:
      - name: sonarqube.example.com

  resources:
    limits:
      cpu: 700m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 1.5Gi

  postgresql:
    enabled: false

  jdbcOverwrite:
    enable: enable
    jdbcUrl: "jdbc:postgresql://postgresql-primary.sonarqube.svc:5432/sonarqube?socketTimeout=1500"
    jdbcUsername: "sonarqube"
    jdbcSecretName: "postgresql-pguser-sonarqube"
    jdbcSecretPasswordKey: "password"
