{{- if .Values.eso.enabled }}
{{- if eq .Values.eso.type "gcpsm" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.eso.secretStoreName }}
spec:
  provider:
    gcpsm:
      projectID: "alphabet-123"
{{- end }}
{{- end }}
