{{ if .Values.nexus-operator.oauth2_proxy.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: nexus
spec:
  advancedProtocolMappers: true
  clientId: nexus
  defaultClientScopes:
    - groups
    - edp
  secret: keycloak-client-nexus-secret
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  webUrl: {{ .Values.nexusUrl }}
{{ end }}
