apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: kibana
spec:
  advancedProtocolMappers: true
  clientId: kibana
  directAccess: true
  public: false
  defaultClientScopes:
    - profile
    - email
    - roles
  targetRealm: "shared"
  webUrl: "https://kibana.example.com"
  protocolMappers:
    - name: roles
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-realm-role-mapper"
      config:
        "access.token.claim": "true"
        "claim.name": "roles"
        "id.token.claim": "true"
        "userinfo.token.claim": "true"
        "multivalued": "true"
