apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: deptrack
spec:
  advancedProtocolMappers: true
  clientId: deptrack
  directAccess: true
  public: true
  defaultClientScopes:
    - profile
    - email
    - roles
  realmRef:
    kind: KeycloakRealm
    name: shared
  webUrl: "https://deptrack.example.com"
  protocolMappers:
    - name: roles
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-realm-role-mapper"
      config:
        "access.token.claim": "true"
        "claim.name": "roles"
        "id.token.claim": "true"
        "userinfo.token.claim": "true"
        "multivalued": "true"
