vault:
  fullnameOverride: vault
  global:
    openshift: true
  server:
    standalone:
      enabled: false
    ha:
      enabled: true
      replicas: 3
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true
          listener "tcp" {
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable = 1
          }

          storage "raft" {
            path = "/vault/data"
              retry_join {
              leader_api_addr = "http://vault-0.vault-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-1.vault-internal:8200"
            }
            retry_join {
              leader_api_addr = "http://vault-2.vault-internal:8200"
            }
          }

          service_registration "kubernetes" {}

    dataStorage:
      enabled: true
      size: 1Gi

    route:
      enabled: true
      activeService: true
      host: vault.example.com
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge

  ui:
    enabled: true

job:
  clusterApiUrl: "https://api.example.com:6443"
  keycloakUrl: "https://keycloak.example.com/auth/realms/shared"

oidc:
  enabled: false

# Configure components of the External Secrets Operator (ESO).
eso:
  # -- Install components of the ESO.
  enabled: true
  # -- Defines provider type. One of `aws` or `gcpsm`.
  type: "aws"
  # -- Defines Secret Store name.
  secretStoreName: "aws-parameterstore"
  # -- Value name in AWS ParameterStore, AWS SecretsManager or GCP Secret Manager.
  secretName: "/edp/system"
