{{ if and .Values.oidc.enabled .Values.eso.enabled }}
{{- $secretName := .Values.eso.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-grafana-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.eso.secretStoreName }}
  data:
  - secretKey: clientSecret
    remoteRef:
      key: {{ $secretName }}
      property: keycloak-client-grafana-secret.clientSecret
{{ end }}
