apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: opensearch
spec:
  defaultClientScopes:
    - role
  clientId: opensearch
  secret: keycloak-client-opensearch-secret
  realmRef:
    kind: KeycloakRealm
    name: main
  webUrl: https://opensearch-dashboards.example.com