keycloakx:
  nameOverride: keycloakx
  fullnameOverride: keycloakx
  replicas: 1

  # The following parameter is unrecommended to expose. Exposed health checks lead to an unnecessary attack vector.
  health:
    enabled: false
  # The following parameter is unrecommended to expose. Exposed metrics lead to an unnecessary attack vector.
  metrics:
    enabled: false

  command:
    - "/opt/keycloak/bin/kc.sh"
    - "--verbose"
    - "start"
    - "--auto-build"
    - "--http-enabled=true"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--hostname-strict-https=false"
    - "--spi-events-listener-jboss-logging-success-level=info"
    - "--spi-events-listener-jboss-logging-error-level=warn"
    - "--import-realm"

  # Additional environment variables for Keycloak.
  # Environment variables "KC_HOSTNAME ADMIN_URL" and "KC_HOSTNAME URL" for working in "passthrough" mode,
  # if they are not defined there will be an eternal loading of "LOGIN ADMIN UI"
  extraEnv: |
    - name: KC_HOSTNAME_URL
      value: "https://keycloak.example.com/auth"
    - name: KC_HOSTNAME_ADMIN_URL
      value: "https://keycloak.example.com/auth"
    - name: KEYCLOAK_ADMIN
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: username
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-admin-creds
          key: password
    - name: JAVA_OPTS_APPEND
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.awt.headless=true
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

  # This block should be uncommented if you install Keycloak on Kubernetes
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/affinity: cookie
    # The following parameter is unrecommended to expose. Admin paths lead to an unnecessary attack vector.
    console:
      enabled: false
    rules:
      - host: keycloak.example.com
        paths:
          - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
            pathType: Prefix

  proxy:
    enabled: true
    mode: "passthrough"

  # This block should be uncommented if you set Keycloak to OpenShift and change the host field
  # route:
  #   enabled: false
  #   # Path for the Route
  #   path: '/'
  #   # Host name for the Route
  #   host: "keycloak.<ROOT_DOMAIN>"
  #   # TLS configuration
  #   tls:
  #     enabled: true

  resources:
    limits:
      memory: "2048Mi"
    requests:
      cpu: "50m"
      memory: "512Mi"

  # Check database readiness at startup
  dbchecker:
    enabled: true

  database:
  # This section configure connection to the external database
  #
  # By default, keycloakx Helm Chart uses Postgres database from PGO.
  # Ref: https://github.com/epam/edp-cluster-add-ons/tree/main/add-ons/keycloak/templates/postgres-cluster.yaml
  # More detail how install PostgreSQL Operator you can find:
  # Ref: https://github.com/epam/edp-cluster-add-ons/tree/main/add-ons/postgres-operator

  # Optional, can use onboarding PostgreSQL database by Helm chart.
  # To use this approach disables creating a database by Postgres operator, flag - Values.pgo.enabled=false
  # Ref: https://github.com/epam/edp-cluster-add-ons/tree/main/add-ons/keycloak-postgresql

  # PGO example (preconfigured by default)
    vendor: postgres
    existingSecret: postgresql-pguser-admin
    hostname: postgresql-primary.security.svc
    port: 5432
    username: admin
    database: keycloak

  # Postgres database Helm chart example
    # vendor: postgres
    # existingSecret: keycloak-postgresql
    # hostname: postgresql
    # port: 5432
    # username: admin
    # database: keycloak

  autoscaling:
    # If `true`, an autoscaling/v2 HorizontalPodAutoscaler resource is created (requires Kubernetes 1.23 or above)
    # Autoscaling seems to be most reliable when using KUBE_PING service discovery (see README for details)
    # This disables the `replicas` field in the StatefulSet
    enabled: true
    # Additional HorizontalPodAutoscaler labels
    labels: {}
    # The minimum and maximum number of replicas for the Keycloak StatefulSet
    minReplicas: 1
    maxReplicas: 3
    # The metrics to use for scaling
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
    # The scaling policy to use. This will scale up quickly but only scale down a single Pod per 5 minutes.
    # This is important because caches are usually only replicated to 2 Pods and if one of those Pods is terminated this will give the cluster time to recover.
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 300

# The section below allows to deploy a new PostgresCluster with the below details:
# Endpoint (Kubernetes service): postgresql-primary.security.svc
# User Secret (Kubernetes Secret): postgresql-pguser-admin
# Ref: https://github.com/epam/edp-cluster-add-ons/tree/main/add-ons/postgres-operator
pgo:
  # -- Enables creating a new database with Postgres operator.
  enabled: true
