apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-admin-ui
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: root-user
    remoteRef:
      key: /edp/harbor-ha
      property: minio.ROOT_USER
  - secretKey: root-password
    remoteRef:
      key: /edp/harbor-ha
      property: minio.ROOT_PASSWORD
