apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: general
  # Add label to the collector. This label will be added to ServiceMonitor and tracked properly by Prometheus.
  labels:
    release: prom
spec:
  # This will create a ServiceMonitor for the OpenTelemetry Collector.
  observability:
    metrics:
      enableMetrics: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug:
      otlp:
        endpoint: "jaeger-operator-jaeger-collector.observability:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          exporters: [debug]
      telemetry:
        metrics:
          address: ":8888"
