apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-shared-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore-oidc
  data:
  - secretKey: clientSecret
    remoteRef:
      key: /edp/keycloak-operator
      property: keycloak-client-shared-secret.clientSecret
